#!/bin/bash

# GPG Agent
gpg-connect-agent /bye
#export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh
export SSH_AUTH_SOCK="/run/user/$(id -u)/gnupg/S.gpg-agent.ssh"

# Activate radeon graphics
#xrandr --setprovideroffloadsink 0x56 0x87
xrandr --setprovideroutputsource 0x56 0x87

# Deactivate system beep
xset -b

# Custom keyboard settings
xmodmap ~/.Xmodmap
