#!/bin/bash

# GPG Agent
gpg-connect-agent /bye
#export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh
export SSH_AUTH_SOCK="/run/user/$(id -u)/gnupg/S.gpg-agent.ssh"

# Activate radeon graphics
# xrandr --setprovideroffloadsink 1 0
# xrandr --setprovideroutputsource 1 0

# Deactivate system beep
xset -b
xset s off -dpms

# Custom keyboard settings
xmodmap ~/.Xmodmap
