# Additional aliases

# Local
alias proc='ps -ef | grep -v grep | grep'
alias i3lock='i3lock --color=000000'

# bépo
alias azer='setxkbmap fr bepo'
alias bépo='setxkbmap fr'

# ls aliases
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'
